#!/usr/bin/env python3
"""Percolator: writes params.json (what MPC sees), src/params_def.h (the engine's table, same order) and layout.conf.

    python3 mpc/gen.py            (from the plugin folder, or anywhere: paths are relative to this file)

The parameter order is the VST index MPC saves projects and Q-Links by: append new parameters at the end.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

KNOBS = [("tune", "TUNE"), ("decay", "DECAY"), ("p1", "PARAM 1"), ("p2", "PARAM 2"),
         ("cutoff", "CUTOFF"), ("drive", "DRIVE"), ("fx", "FX SEND"), ("level", "LEVEL")]
ALGOS = {1: ["FOLD", "WAVE", "RES BD"], 2: ["FOLD", "WAVE", "FM"], 3: ["SNARE", "SLAP", "TOM"],
         4: ["NOISE", "METAL", "SAMPLE"]}
DEPTHS = ["OFF"] + ["%d%%" % (10 * i) for i in range(1, 9)]
WAVES = ["SINE", "TRI", "RAMP", "SAW", "SQUARE", "S&H", "DRIFT"]

# the Init kit (also the engine's defaults): 0..100 for knobs, option index for switches
INIT = {
    1: dict(tune=38, decay=22, p1=18, p2=34, cutoff=60, drive=18, fx=0, level=85, algo=0, mode=0, vcf=2),
    2: dict(tune=48, decay=20, p1=35, p2=25, cutoff=75, drive=10, fx=12, level=70, algo=2, mode=0, vcf=2),
    3: dict(tune=45, decay=18, p1=55, p2=35, cutoff=80, drive=15, fx=10, level=75, algo=0, mode=0, vcf=2),
    4: dict(tune=55, decay=6, p1=10, p2=0, cutoff=45, drive=0, fx=0, level=60, algo=0, mode=0, vcf=0),
}


def params():
    P = []

    def knob(key, name, default, **kw):
        P.append(dict(key=key, name=name, min=0, max=100, default=default, **kw))

    def opts(key, name, options, default=0, **kw):
        P.append(dict(key=key, name=name, options=options, default=options[default], **kw))

    # clamped: the engine holds KIT to the kits it has loaded (8 built in + the packs found)
    P.append(dict(key="kit", name="KIT", type="stepper", min=0, max=511, step=1, default=0, display="int", clamped=True))
    P.append(dict(key="kit_prev", name="PREV KIT", momentary=True, step_of="kit", step_delta=-1))
    P.append(dict(key="kit_next", name="NEXT KIT", momentary=True, step_of="kit", step_delta=1))
    P.append(dict(key="kit_name", name="KIT NAME", min=0, max=0, display="string", type="readout"))
    for v in range(1, 5):
        for k, n in KNOBS:
            extra = {}
            if k in ("p1", "p2"):
                extra["dynamic_name"] = True
            if k in ("tune", "decay", "p1", "p2", "cutoff"):
                extra["dynamic_display"] = True
            knob("v%d_%s" % (v, k), "V%d %s" % (v, n), INIT[v][k], **extra)
        opts("v%d_algo" % v, "V%d ALGO" % v, ALGOS[v], INIT[v]["algo"])
        opts("v%d_mode" % v, "V%d MODE" % v, ["1", "2", "3"], INIT[v]["mode"], dynamic_display=True)
        opts("v%d_vcf" % v, "V%d VCF" % v, ["HP", "BP", "LP"], INIT[v]["vcf"])
    knob("fx_time", "BBD TIME", 45, dynamic_display=True)
    knob("fx_feedback", "FEEDBACK", 35)
    knob("fx_rate", "BBD LFO RATE", 30, dynamic_display=True)
    knob("fx_depth", "BBD MOD DEPTH", 10)
    opts("fx_range", "BBD RANGE", ["SHORT", "LONG"], 1)
    opts("fx_colour", "BBD COLOUR", ["DARK", "BRIGHT"], 0)
    knob("volume", "VOLUME", 71)
    knob("comp_thresh", "COMP THRESH", 0, dynamic_display=True)
    knob("comp_amt", "COMP AMOUNT", 0)
    knob("lfo_speed", "LFO SPEED", 40, dynamic_display=True)
    opts("lfo_wave", "LFO WAVE", WAVES, 0)
    knob("lfo_level", "MOD LEVEL", 100)
    opts("keys", "KEYS", ["OFF", "V1", "V2", "V3", "V4"], 0)
    for v in range(1, 5):
        for k, n in KNOBS:
            opts("v%d_m_%s" % (v, k), "V%d MOD %s" % (v, n), DEPTHS, 0)
    return P


def write_header(P):
    lines = ["/* generated by mpc/gen.py: do not edit (change gen.py and run it) */", "#pragma once",
             "/* kind: 0 = knob 0..100, 1 = option list (value = index), 2 = kit number, 3 = not a stored value */",
             "typedef struct { const char *key; int kind; int nopts; float def; } pdef_t;",
             "static const pdef_t PDEF[] = {"]
    enum = []
    for i, p in enumerate(P):
        if "options" in p:
            kind, n, d = 1, len(p["options"]), p["options"].index(p["default"])
        elif p["key"] == "kit":
            kind, n, d = 2, 0, 0
        elif p.get("momentary") or p.get("display") == "string":
            kind, n, d = 3, 0, 0
        else:
            kind, n, d = 0, 0, p["default"]
        lines.append('    {"%s", %d, %d, %.1ff},' % (p["key"], kind, n, d))
        enum.append("P_%s = %d," % (p["key"].upper(), i))
    lines += ["};", "enum {"] + ["    " + e for e in enum] + ["    NP = %d" % len(P), "};"]
    lines += ["/* per-voice block: v%d_tune is P_V1_TUNE + 11 * (v - 1) */", "#define VSTRIDE 11",
              "#define MSTRIDE 8"]
    open(os.path.join(ROOT, "src", "params_def.h"), "w").write("\n".join(lines) + "\n")


# ---- the screen ----------------------------------------------------------------------------------------------
# Plugin area: x 0..1280, y 86..714 (the artwork's y = layout y - 86). Five tabs, one Q-Link page each (no sub-pages
# to swipe between): V1+V2, V3+V4, MASTER, MOD 1+2, MOD 3+4. A voice panel: its envelope display and switches, then
# two rows of four knobs; each row is one Q-Link column (Moog's layout is the model), outlined by a row plate.
# The artwork (mpc/skin.py, in the art container) is drawn from build/skin.json, written here with the layout.
THEME = """theme_bg=0b0a10
theme_panel=15141c
theme_line=34323f
theme_ink=f3f0ff
theme_ink_dim=aba7c4
theme_ink_faint=6a6782
theme_accent=b48cff
theme_accent_hi=d9c6ff
theme_box=0d0c13
theme_lcd=07060b
theme_seg_active=b48cff
theme_seg_active_tx=0b0a10
theme_seg_inactive=24232e
theme_btn_bg=2a2838
theme_btn_text=f3f0ff
theme_knob_face=26252f
theme_knob_ring=3a3848
theme_knob_dot=b48cff
theme_display_bezel=050407
theme_display_bg=0d0a10
theme_display_cell=21160f
theme_display_ink=ffb13d
theme_display_off=2b1c10
art_css=percolator.css
qlink_bounds=column
qlink_box=slot
label_scale=1
focus_ring=1
"""
COL = {1: "#ff5a1f", 2: "#ff2bd6", 3: "#18e0ff", 4: "#b6ff2b", "kit": "#ffb13d", "bbd": "#3d8bff",
       "mst": "#a07bff", "mod": "#ffd23f"}

# PARAM 1 / PARAM 2 names per voice and algorithm (src/voices.c algo_p_name), for the captions in the screenshots;
# on the MPC the engine names them live as the algorithm changes
PNAMES = {1: [("FOLD", "PITCH ENV"), ("WAVE POS", "PITCH ENV"), ("ENV TIME", "PITCH ENV")],
          2: [("FOLD", "PITCH ENV"), ("WAVE POS", "PITCH ENV"), ("FM", "PITCH ENV")],
          3: [("NOISE TONE", "NOISE DECAY"), ("REVERB", "FILTER"), ("FM", "TONE")],
          4: [("REVERB", "ATTACK"), ("REVERB", "ATTACK"), ("CRUSH", "ATTACK")]}


def caption(v, k):
    if k in ("p1", "p2"):
        return "V%d %s" % (v, PNAMES[v][INIT[v]["algo"]][k == "p2"])
    return "V%d %s" % (v, dict(KNOBS)[k])


# ---- artwork (HTML for mpc/skin.py; absolute layout coordinates in, artwork coordinates out) -----------------------
CSS = """*{box-sizing:border-box}
body{margin:0;width:1280px;height:628px;overflow:hidden;position:relative;font-family:"Titillium Web",sans-serif;
background:radial-gradient(ellipse 85% 75% at 50% 35%,#18141f 0%,#0c0b11 55%,#060609 100%)}
body:after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,rgba(255,255,255,.014) 0 1px,
transparent 1px 3px)}
.a{position:absolute}
.t{position:absolute;white-space:nowrap;line-height:1}
"""


def rgba(c, a):
    c = c.lstrip("#")
    return "rgba(%d,%d,%d,%.3f)" % (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), a)


def h_panel(x, y, w, h, c, title, sub=""):
    y -= 86
    o = ('<div class="a" style="left:%dpx;top:%dpx;width:%dpx;height:%dpx;border-radius:16px;'
         'background:linear-gradient(180deg,#1b1a25 0%%,#111018 100%%);border:1.5px solid %s;'
         'box-shadow:0 0 24px %s,inset 0 1px 0 rgba(255,255,255,.06)"></div>' % (x, y, w, h, rgba(c, .6), rgba(c, .25)))
    o += ('<div class="a" style="left:%dpx;top:%dpx;width:%dpx;height:3px;border-radius:2px;'
          'background:linear-gradient(90deg,%s,%s 60%%,transparent);box-shadow:0 0 10px %s"></div>'
          % (x + 16, y + 1, w - 32, c, rgba(c, .35), rgba(c, .8)))
    o += ('<div class="t" style="left:%dpx;top:%dpx;display:flex;align-items:baseline;gap:14px">'
          '<span style="font-size:22px;font-weight:700;letter-spacing:.22em;color:%s;text-shadow:0 0 12px %s">%s</span>'
          '<span style="font-size:13px;font-weight:600;letter-spacing:.16em;color:#8f8ba8">%s</span></div>'
          % (x + 20, y + 14, c, rgba(c, .7), title, sub))
    return o


def h_text(x, y, s, c="#aba7c4", size=12, spacing=.16, weight=700):
    return ('<div class="t" style="left:%dpx;top:%dpx;font-size:%dpx;font-weight:%d;letter-spacing:%gem;color:%s">%s</div>'
            % (x, y - 86, size, weight, spacing, c, s))


def h_plate(x, y, w, h, c):
    return ('<div class="a" style="left:%dpx;top:%dpx;width:%dpx;height:%dpx;border-radius:12px;'
            'background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.012));border:1px solid %s"></div>'
            % (x, y - 86, w, h, rgba(c, .2)))


def h_display(x, y, w, h, c, cols):
    """The envelope display's glass: grid, a divider between its columns, each column's caption."""
    o = ('<div class="a" style="left:%dpx;top:%dpx;width:%dpx;height:%dpx;border-radius:10px;background-color:#050508;'
         'background-image:linear-gradient(%s 1px,transparent 1px),linear-gradient(90deg,%s 1px,transparent 1px);'
         'background-size:27px 20px;background-position:10px 20px;border:1px solid %s;'
         'box-shadow:inset 0 2px 12px #000,0 0 14px %s"></div>' % (x, y - 86, w, h, rgba(c, .07), rgba(c, .07),
                                                                 rgba(c, .4), rgba(c, .14)))
    cx = x + 10
    for i, (cw, lab) in enumerate(cols):
        if i:
            o += ('<div class="a" style="left:%dpx;top:%dpx;width:0;height:%dpx;border-left:1px dashed %s"></div>'
                  % (cx, y - 86 + 8, h - 16, rgba(c, .3)))
        o += h_text(cx + 6, y + 6, lab, rgba(c, .8), 10, .18)
        cx += cw
    return o


def layout():
    L = ["# Percolator, generated by mpc/gen.py (do not edit by hand: change gen.py and run it again).", THEME]
    NAME = {p["key"]: p["name"] for p in params()}
    ROWS = (("tune", "decay", "p1", "p2"), ("cutoff", "drive", "fx", "level"))
    PX, PW, PY, PH = (8, 648), 624, 94, 612
    KY = (392, 572)                  # knob rows; each row's touch boxes end by y 664 (the plugin area ends at 714)
    DX, DY, DW, DH = 16, 142, 344, 148   # the display (x relative to the panel)
    SY = (166, 216, 266)             # ALGO / MODE / VCF
    art = {"out": os.path.join(ROOT, "images", "skin"), "css": CSS, "display_frames": 32,
           "fonts": os.path.join(os.path.dirname(os.path.dirname(ROOT)), "framework", "mpc-vst-plugins", "tools",
                                 "html_art", "fonts"),
           "bgs": [], "knobs": [], "segs": [], "displays": []}
    segs = set()

    def seg(col, w, h):   # a switch segment image, unlit (col None) or lit in a colour
        name = "seg_%s_%dx%d" % (col or "off", w, h)
        if name not in segs:
            segs.add(name)
            art["segs"].append({"name": name, "w": w, "h": h, "color": COL.get(col) if col else None})
        return "images/skin/%s.png" % name

    def enum(kind, cx, cy, key, col, sw, sh, label=""):
        L.append('%s cx=%d cy=%d label="%s" key=%s sw=%d sh=%d img=%s img_on=%s'
                 % (kind, cx, cy, label, key, sw, sh, seg(None, sw, sh), seg(col, sw, sh)))

    for col, r in ((1, 36), (2, 36), (3, 36), (4, 36), ("bbd", 40), ("mst", 40), ("mod", 40)):
        art["knobs"].append({"name": "knob_%s" % col, "r": r, "color": COL[col]})

    def knob(key, x, y, col, r, label=None):
        L.append('knob cx=%d cy=%d r=%d label="%s" key=%s strip=images/skin/knob_%s.png frames=64'
                 % (x, y, r, label or NAME[key], key, col))

    def voice_panel(px, v, title, sub):
        c = COL[v]
        h = h_panel(px, PY, PW, PH, c, title, sub)
        for y in KY:
            h += h_plate(px + 12, y - 58, PW - 24, 156, c)
        return h

    # voice tabs
    for pair in ((1, 2), (3, 4)):
        L.append("[tab V%d+V%d]" % pair)
        L.append("art file=images/skin/bg_v%d%d.png x=0 y=86 w=1280 h=628" % pair)
        html = ""
        for px, v in zip(PX, pair):
            c = COL[v]
            html += voice_panel(px, v, "VOICE %d" % v, "PAD %d" % v)
            # the display: PITCH | AMP (voices 1-2), AMP (3), ATTACK | DECAY (4)
            cols = {1: [(108, "PITCH"), (216, "AMP")], 2: [(108, "PITCH"), (216, "AMP")], 3: [(324, "AMP")],
                    4: [(108, "ATTACK"), (216, "DECAY")]}[v]
            html += h_display(px + DX, DY, DW, DH, c, cols)
            mx, my, mh = px + DX + 10, DY + 20, DH - 28
            keys = {1: ["p2", "decay"], 2: ["p2", "decay"], 3: ["decay"], 4: ["p2", "decay"]}[v]
            for (cw, lab), k in zip(cols, keys):
                kind = {"PITCH": "pitch", "ATTACK": "attack"}.get(lab, "decay")
                name = "env_v%d_%s" % (v, kind)
                art["displays"].append({"name": name, "kind": kind, "w": cw, "h": mh, "color": c, "attack": v != 4})
                L.append("meter cx=%d cy=%d w=%d h=%d key=v%d_%s strip=images/skin/%s.png frames=32"
                         % (mx + cw // 2, my + mh // 2, cw, mh, v, k, name))
                mx += cw
            # ALGO / MODE / VCF, lit in the voice's colour; the mode's name in the title bar
            for y, (k, lab) in zip(SY, (("algo", "ALGO"), ("mode", "MODE"), ("vcf", "VCF"))):
                html += h_text(px + 380, y - 7, lab)
                enum("enum_h", px + 520, y, "v%d_%s" % (v, k), v, 60, 30)
            L.append("readout cx=%d cy=%d w=200 h=24 vs=18 ink=ink box=no key=v%d_mode" % (px + 520, PY + 27, v))
            for y, ks in zip(KY, ROWS):
                for i, k in enumerate(ks):
                    knob("v%d_%s" % (v, k), px + 78 + 156 * i, y, v, 36, caption(v, k))
        art["bgs"].append({"name": "bg_v%d%d" % pair, "html": html})
        L.append('qlinks "V%d+V%d" = ' % pair + ",".join("v%d_%s" % (v, k) for v in pair for ks in ROWS for k in ks))
        L.append("")

    # MASTER page: the kit browser, then a panel per Q-Link column: BBD delay, master (with KEYS), modulation
    L.append("[tab MASTER]")
    L.append("art file=images/skin/bg_master.png x=0 y=86 w=1280 h=628")
    html = h_panel(8, 94, 1264, 152, COL["kit"], "KIT")
    html += h_panel(8, 256, 494, 450, COL["bbd"], "BBD DELAY")
    html += h_panel(512, 256, 376, 450, COL["mst"], "MASTER")
    html += h_panel(898, 256, 374, 450, COL["mod"], "MODULATION")
    art["bgs"].append({"name": "bg_master", "html": html})
    L.append('stepper cx=520 cy=180 w=760 h=78 label="" key=kit get=kit_name style=dotmatrix')
    L.append('button cx=1010 cy=180 w=120 h=60 label="PREV" key=kit_prev')
    L.append('button cx=1150 cy=180 w=120 h=60 label="NEXT" key=kit_next')
    knob("fx_time", 90, 362, "bbd", 40)
    knob("fx_feedback", 90, 562, "bbd", 40)
    knob("fx_rate", 250, 362, "bbd", 40)
    knob("fx_depth", 250, 562, "bbd", 40)
    enum("enum_v", 410, 382, "fx_range", "bbd", 110, 30, "RANGE")
    enum("enum_v", 410, 582, "fx_colour", "bbd", 110, 30, "COLOUR")
    knob("volume", 600, 362, "mst", 40)
    knob("comp_thresh", 600, 562, "mst", 40)
    knob("comp_amt", 790, 562, "mst", 40)
    enum("enum_v", 790, 427, "keys", "mst", 100, 26, "KEYS")
    knob("lfo_speed", 990, 362, "mod", 40)
    knob("lfo_level", 990, 562, "mod", 40)
    L.append('popup cx=1170 cy=374 w=160 h=48 label="WAVE" key=lfo_wave')
    L.append('qlinks "MASTER" = fx_time,fx_feedback,fx_rate,fx_depth,volume,comp_thresh,comp_amt,keys,'
             'lfo_speed,lfo_level,lfo_wave,-,kit')
    L.append("")

    # MOD pages: the LFO depth of each voice knob (the hardware's MODULATION DESTINATION / DEPTH), each where its knob
    # is on the voice tabs
    for pair in ((1, 2), (3, 4)):
        L.append("[tab MOD %d+%d]" % pair)
        L.append("art file=images/skin/bg_mod%d%d.png x=0 y=86 w=1280 h=628" % pair)
        html = ""
        for px, v in zip(PX, pair):
            html += voice_panel(px, v, "VOICE %d" % v, "LFO DEPTH")
            html += h_text(px + 22, 150, "HOW FAR THE LFO MOVES EACH KNOB", "#aba7c4", 13, .14, 600)
            html += h_text(px + 22, 172, "MOD LEVEL SCALES THEM ALL (MASTER PAGE)", "#6a6782", 12, .14, 600)
            # the LFO itself, live (set on the MASTER page)
            html += h_display(px + DX, 204, PW - 2 * DX, 104, COL[v], [])
            for i, (k, lab) in enumerate((("lfo_wave", "LFO WAVE"), ("lfo_speed", "SPEED"), ("lfo_level", "MOD LEVEL"))):
                x = px + DX + 20 + i * 196
                html += h_text(x, 220, lab, rgba(COL[v], .8), 11, .18)
                L.append("readout cx=%d cy=%d w=180 h=30 vs=22 ink=ink box=no key=%s" % (x + 86, 268, k))
            for y, ks in zip(KY, ROWS):
                for i, k in enumerate(ks):
                    L.append('popup cx=%d cy=%d w=124 h=46 label="%s" key=v%d_m_%s'
                             % (px + 78 + 156 * i, y + 26, dict(KNOBS)[k], v, k))
        art["bgs"].append({"name": "bg_mod%d%d" % pair, "html": html})
        L.append('qlinks "MOD %d+%d" = ' % pair + ",".join("v%d_m_%s" % (v, k) for v in pair for ks in ROWS for k in ks))
        L.append("")
    # Q-Links fixed to the track: a column per voice
    L.append("qlinks_track = " + ",".join("v%d_%s" % (v, k) for v in range(1, 5) for k in ("tune", "decay", "p1", "cutoff")))
    open(os.path.join(ROOT, "layout.conf"), "w").write("\n".join(L) + "\n")
    os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
    json.dump(art, open(os.path.join(ROOT, "build", "skin.json"), "w"), indent=1)


if __name__ == "__main__":
    P = params()
    json.dump({"name": "Percolator", "params": P}, open(os.path.join(ROOT, "params.json"), "w"), indent=1)
    write_header(P)
    layout()
    print("params.json: %d parameters; src/params_def.h; layout.conf; build/skin.json (then mpc/skin.py)" % len(P))
