/* Band-limited analog waveforms (sub oscillator) + noise — de-JUCE'd port of
 * gin::BandLimitedLookupTables, gin::StereoOscillator, gin::WhiteNoise and
 * gin::PinkNoise (BSD-3, Roland Rabien; PinkNoise MIT, (c) 2020 Thomas
 * Merchant, Voss-McCartney).
 *
 * Two deliberate deviations from gin, both noted inline:
 *  1. Mip levels are DECIMATED like our wavetables (levels are generated by
 *     formula at the decimated size, so this also cuts the additive-synthesis
 *     build cost ~6x). Same audible content.
 *  2. gin's processSquare/processPulse compute their table index as
 *     (note-0.5)/tableCount — an obvious copy-paste slip (every other shape
 *     divides by notesPerTable, and the adjacent std::min compares a value
 *     with itself). We use notesPerTable. Audible only on high-note pulses.
 */
#pragma once

#include "wavetable.h"   /* MipLevel, FrameTable, midiNoteToHz */
#include "fft.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <random>

namespace tb {

enum class Wave {
    silence = 0, sine, triangle, sawUp, sawDown, pulse, square,
    whiteNoise, pinkNoise,
};

/* ---- gin's additive generators, verbatim ---- */
namespace waves {

inline int oddEven(int x) { return (x % 2 == 0) ? 1 : -1; }

inline float sine(float phase, float, float)
{
    return std::sin(phase * 2.0f * (float) M_PI);
}

inline float triangle(float phase, float freq, float sampleRate)
{
    float sum = 0.0f, k = 1.0f;
    while (freq * k < sampleRate / 2) {
        sum += std::pow(-1.0f, (k - 1) / 2.0f) / (k * k)
             * std::sin(k * (phase * 2.0f * (float) M_PI));
        k += 2;
    }
    return 8.0f / ((float) M_PI * (float) M_PI) * sum;
}

inline float sawUp(float phase, float freq, float sampleRate)
{
    float sum = 0.0f, fk = 1.0f;
    int k = 1;
    while (freq * k < sampleRate / 2) {
        sum += oddEven(k) * std::sin(fk * (phase * 2.0f * (float) M_PI)) / fk;
        k++; fk++;
    }
    return -2.0f / (float) M_PI * sum;
}

inline float sawDown(float phase, float freq, float sampleRate)
{
    return -sawUp(phase, freq, sampleRate);
}

} // namespace waves

/* ---- noise, verbatim ---- */

class WhiteNoise {
public:
    WhiteNoise() { std::random_device rd; generator.seed(rd()); }
    inline float nextSample() { return dist(generator); }
private:
    std::default_random_engine generator;
    std::normal_distribution<float> dist { 0.0f, 0.1f };
};

class PinkNoise {
public:
    PinkNoise()
    {
        rnd.s = 0x2252e7cd98846fddULL;
        rnd.x = 0; rnd.w = 0;
        counter = 0;
        std::memset(octaveHold, 0, sizeof octaveHold);
        out = 0.0f;
    }
    float nextSample()
    {
        uint8_t octave = kTrailingZeros[counter];
        out -= octaveHold[octave];
        octaveHold[octave] = (float) nextInt() / (float) INT32_MAX;
        octaveHold[octave] /= (float) (10 - octave);
        out += octaveHold[octave];
        counter++;
        return out;
    }
private:
    struct { uint64_t s, x, w; } rnd;
    int32_t nextInt()
    {
        rnd.x *= rnd.x;
        rnd.x += (rnd.w += rnd.s);
        rnd.x = (rnd.x >> 32u) | (rnd.x << 32u);
        return (int32_t) rnd.x;
    }
    static constexpr uint8_t kTrailingZeros[256] = {
        8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
        5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
    };
    float out;
    float octaveHold[9];
    uint8_t counter;
};

/* ---- the table set ---- */

class AnalogTables {
public:
    explicit AnalogTables(double sampleRate_ = 44100.0, int notesPerTable_ = 3,
                          int tableSize_ = 2048)
    {
        build(sampleRate_, notesPerTable_, tableSize_);
    }

    void build(double sampleRate_, int notesPerTable_ = 3, int tableSize_ = 2048)
    {
        sampleRate = sampleRate_;
        notesPerTable = notesPerTable_;
        tableSize = tableSize_;
        buildTable(sawUpTable,    Spectrum::sawUp,    notesPerTable);
        buildTable(sawDownTable,  Spectrum::sawDown,  notesPerTable);
        buildTable(triangleTable, Spectrum::triangle, notesPerTable);
        buildTable(sineTable,     Spectrum::sine,     64);   /* gin: npt=64 */
    }

    inline float processSine(float note, float phase) const
    {
        return sineTable.processLinear(note, phase);
    }
    inline float processTriangle(float note, float phase) const
    {
        return triangleTable.processLinear(note, phase);
    }
    inline float processSawUp(float note, float phase) const
    {
        return sawUpTable.processLinear(note, phase);
    }
    inline float processSawDown(float note, float phase) const
    {
        return sawDownTable.processLinear(note, phase);
    }
    inline float processSquare(float note, float phase) const
    {
        float up = phase + 0.25f, dn = phase - 0.25f;
        if (up >= 1.0f) up -= 1.0f;
        if (dn <  0.0f) dn += 1.0f;
        /* corrected table index — see header comment (2) */
        return sawDownTable.processLinear(note, dn) +
               sawUpTable.processLinear(note, up);
    }
    inline float processPulse(float note, float phase, float pw) const
    {
        pw = std::clamp(pw, 0.01f, 0.99f);
        float up = phase + 0.5f * pw, dn = phase - 0.5f * pw;
        if (up >= 1.0f) up -= 1.0f;
        if (dn <  0.0f) dn += 1.0f;
        if (dn >= 1.0f) dn -= 1.0f;
        float dc = 2.0f * pw - 1.0f;
        return -dc + sawDownTable.processLinear(note, dn) +
                     sawUpTable.processLinear(note, up);
    }

    inline float process(Wave wave, float note, float phase, float pw)
    {
        switch (wave) {
        case Wave::silence:    return 0.0f;
        case Wave::sine:       return processSine(note, phase);
        case Wave::triangle:   return processTriangle(note, phase);
        case Wave::sawUp:      return processSawUp(note, phase);
        case Wave::sawDown:    return processSawDown(note, phase);
        case Wave::pulse:      return processPulse(note, phase, pw);
        case Wave::square:     return processSquare(note, phase);
        case Wave::whiteNoise: return white.nextSample();
        case Wave::pinkNoise:  return pink.nextSample();
        default:               return 0.0f;
        }
    }

    size_t bytes() const
    {
        return sineTable.bytes() + sawUpTable.bytes() +
               sawDownTable.bytes() + triangleTable.bytes();
    }

public:
    /* Sine-series amplitude of harmonic k for each waveform — the analytic
     * spectra behind gin's additive generators (identical coefficients). */
    enum class Spectrum { sine, triangle, sawUp, sawDown };
    static float harmonicAmp(Spectrum s, int k)
    {
        switch (s) {
        case Spectrum::sine:
            return k == 1 ? 1.0f : 0.0f;
        case Spectrum::triangle:
            if ((k & 1) == 0) return 0.0f;
            return 8.0f / ((float) M_PI * (float) M_PI)
                 * (((k - 1) / 2) % 2 == 0 ? 1.0f : -1.0f) / (float) (k * k);
        case Spectrum::sawUp:
            return -2.0f / (float) M_PI * (k % 2 == 0 ? 1.0f : -1.0f) / (float) k;
        case Spectrum::sawDown:
            return  2.0f / (float) M_PI * (k % 2 == 0 ? 1.0f : -1.0f) / (float) k;
        }
        return 0.0f;
    }

private:
    static int nextPow2i(int v) { int p = 1; while (p < v) p <<= 1; return p; }

    /* Build a table via inverse FFT of the analytic spectrum — O(S log S) per
     * level instead of O(S x harmonics). Output is identical to the additive
     * sum up to the table's own Nyquist; beyond it gin's additive evaluation
     * could only fold harmonics back in as aliases, which we drop instead
     * (affects only sub-audio notes below MIDI ~6). The 2.7 s on-device
     * additive build becomes a few ms. */
    void buildTable(FrameTable &ft, Spectrum s, int npt)
    {
        ft.levels.clear();
        ft.notesPerTable = npt;
        std::vector<Cpx> spec;
        for (float note = (float) npt + 0.5f; note < 127.0f; note += (float) npt) {
            const float freq = midiNoteToHz(note);
            int harmonics = 0;      /* gin's loop condition: freq * k < sr/2 */
            while (freq * (harmonics + 1) < (float) sampleRate / 2.0f) harmonics++;
            if (harmonics < 1) harmonics = 1;

            int S = nextPow2i(2 * (harmonics + 1));
            if (S < 32) S = 32;
            if (S > tableSize) S = tableSize;
            const int kmax = std::min(harmonics, S / 2 - 1);

            spec.assign((size_t) S, Cpx{});
            for (int k = 1; k <= kmax; k++) {
                float a = harmonicAmp(s, k);
                if (a == 0.0f) continue;
                /* A sin(k th) = A/(2i) e^{ik th} - A/(2i) e^{-ik th} */
                spec[(size_t) k]       = { 0.0f, -0.5f * a };
                spec[(size_t) (S - k)] = { 0.0f,  0.5f * a };
            }
            fftRadix2(spec.data(), S, true);

            MipLevel lvl;
            lvl.size = S;
            lvl.data.resize((size_t) S + 1);
            for (int i = 0; i < S; i++)
                lvl.data[(size_t) i] = spec[(size_t) i].re;
            lvl.data[(size_t) S] = lvl.data[0];
            ft.levels.push_back(std::move(lvl));
        }
    }

    double sampleRate = 44100.0;
    int notesPerTable = 3, tableSize = 2048;
    FrameTable sineTable, sawUpTable, sawDownTable, triangleTable;
    WhiteNoise white;
    PinkNoise pink;
};

/* ---- gin::StereoOscillator (the sub + noise voice sources) ---- */

class StereoOscillator {
public:
    explicit StereoOscillator(AnalogTables &t) : tables(t) {}

    struct Params {
        Wave wave = Wave::sawUp;
        float leftGain = 1.0f, rightGain = 1.0f;
        float pw = 0.5f;
        float fold = 0.0f, asym = 0.0f;
    };

    void setSampleRate(double sr) { sampleRate = sr; }
    void noteOn(float p = -1.0f)
    {
        phase = (p >= 0.0f) ? p : (float) rand() / (float) RAND_MAX;
    }

    void processAdding(float note, const Params &params, float *l, float *r, int n)
    {
        float freq = (float) std::min(sampleRate / 2.0,
                                      440.0 * std::pow(2.0, (note - 69.0) / 12.0));
        float delta = freq / (float) sampleRate;

        for (int i = 0; i < n; i++) {
            float s = tables.process(params.wave, note,
                                     std::min(0.99999994f, phase), params.pw);
            postProcess(params, s);
            l[i] += s * params.leftGain;
            r[i] += s * params.rightGain;
            phase += delta;
            while (phase >= 1.0f) phase -= 1.0f;
        }
    }

private:
    inline void postProcess(const Params &p, float &v) const
    {
        if (p.asym > 0.0f) {
            float t = p.asym * p.asym;
            float shaped = ((v - 1.0f) * (v - 1.0f)) * ((v - 1.0f) * (v - 1.0f)) * -1.0f + 1.0f;
            v = v + t * (shaped - v);
        }
        if (p.fold > 0.0f) {
            const float fold = ((1.0f - p.fold) * (1.0f - p.fold)) *
                               ((1.0f - p.fold) * (1.0f - p.fold)) * 1.5f;
            v = v - (std::max(v, fold) - fold) * 2.0f - (std::min(v, -fold) + fold) * 2.0f;
        }
    }

    AnalogTables &tables;
    double sampleRate = 44100.0;
    float phase = 0.0f;
};

} // namespace tb
