/* GENERATED by presets/gen_presets.py from presets/bank.json -- do not edit. */
#ifndef HANK_PRESETS_H
#define HANK_PRESETS_H

namespace hank {

struct PresetDef { const char *name; const char *cat; float v[16]; };

static const PresetDef HANK_PRESETS[] = {
    { "round bass", "bass", { 1.0f, 0.38f, 0.18f, 0.6f, 0.0f, 0.68f, 0.6f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.714f } },
    { "sub", "bass", { 1.0f, 0.08f, 0.0f, 0.45f, 0.0f, 0.78f, 0.85f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.654f } },
    { "growl bass", "bass", { 3.0f, 0.72f, 0.62f, 0.58f, 0.0f, 0.72f, 0.7f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "pluck bass", "bass", { 4.0f, 0.45f, 0.2f, 0.6f, 0.0f, 0.48f, 0.12f, 0.08f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.962f } },
    { "clank bass", "bass", { 10.0f, 0.5f, 0.58f, 0.55f, 0.0f, 0.5f, 0.1f, 0.32f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "e piano", "keys", { 3.0f, 0.52f, 0.05f, 0.78f, 0.0f, 0.74f, 0.28f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.714f } },
    { "marimba", "keys", { 6.0f, 0.48f, 0.0f, 0.86f, 0.0f, 0.66f, 0.0f, 0.05f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.746f } },
    { "wood key", "keys", { 5.0f, 0.42f, 0.18f, 0.7f, 0.0f, 0.52f, 0.05f, 0.18f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.842f } },
    { "clav", "keys", { 7.0f, 0.72f, 0.38f, 0.75f, 0.0f, 0.44f, 0.08f, 0.1f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "soft key", "keys", { 1.0f, 0.32f, 0.0f, 0.72f, 0.552f, 0.8f, 0.45f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.752f } },
    { "thimble", "bell", { 12.0f, 0.45f, 0.05f, 0.9f, 0.0f, 0.82f, 0.05f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.69f } },
    { "big bell", "bell", { 9.0f, 0.52f, 0.12f, 0.85f, 0.0f, 0.95f, 0.1f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.664f } },
    { "glass", "bell", { 14.0f, 0.3f, 0.0f, 0.95f, 0.1f, 0.88f, 0.15f, 0.05f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.694f } },
    { "gamelan", "bell", { 11.0f, 0.6f, 0.3f, 0.8f, 0.0f, 0.86f, 0.06f, 0.12f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.758f } },
    { "brass", "lead", { 2.0f, 0.68f, 0.48f, 0.68f, 0.716f, 0.72f, 0.8f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "reed lead", "lead", { 3.0f, 0.68f, 0.42f, 0.72f, 0.577f, 0.7f, 0.78f, 0.06f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "square lead", "lead", { 1.0f, 0.86f, 0.22f, 0.78f, 0.423f, 0.68f, 0.85f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.734f } },
    { "sync lead", "lead", { 13.0f, 0.75f, 0.55f, 0.8f, 0.0f, 0.66f, 0.7f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "soft pad", "pad", { 1.0f, 0.2f, 0.0f, 0.68f, 0.877f, 0.92f, 0.8f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.666f } },
    { "breath pad", "pad", { 2.0f, 0.3f, 0.05f, 0.7f, 0.845f, 0.9f, 0.72f, 0.38f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.586f } },
    { "glass pad", "pad", { 12.0f, 0.24f, 0.0f, 0.88f, 0.804f, 0.94f, 0.6f, 0.1f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.628f } },
    { "dark pad", "pad", { 0.0f, 0.28f, 0.3f, 0.42f, 0.95f, 0.95f, 0.88f, 0.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.658f } },
    { "swell", "pad", { 3.0f, 0.4f, 0.2f, 0.75f, 0.974f, 0.93f, 0.68f, 0.15f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.682f } },
    { "tom", "perc", { 2.0f, 0.3f, 0.25f, 0.45f, 0.0f, 0.62f, 0.0f, 0.45f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.698f } },
    { "snare", "perc", { 8.0f, 0.45f, 0.35f, 0.72f, 0.0f, 0.58f, 0.05f, 0.85f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.264f } },
    { "rim click", "perc", { 13.0f, 0.55f, 0.5f, 0.8f, 0.0f, 0.34f, 0.0f, 0.45f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "closed hat", "perc", { 15.0f, 0.2f, 0.1f, 0.95f, 0.0f, 0.42f, 0.0f, 1.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.196f } },
    { "open hat", "perc", { 15.0f, 0.22f, 0.1f, 0.93f, 0.0f, 0.7f, 0.15f, 1.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.174f } },
    { "shaker", "perc", { 14.0f, 0.1f, 0.0f, 1.0f, 0.325f, 0.45f, 0.0f, 1.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.186f } },
    { "zap", "fx", { 15.0f, 0.85f, 0.7f, 0.85f, 0.0f, 0.38f, 0.0f, 0.25f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } },
    { "wind", "fx", { 0.0f, 0.1f, 0.0f, 0.55f, 1.0f, 0.96f, 0.9f, 1.0f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.174f } },
    { "drone", "fx", { 7.0f, 0.7f, 0.65f, 0.44f, 0.902f, 0.97f, 0.92f, 0.2f, 1.0f, 8.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.9f } }
};
static const int HANK_PRESET_COUNT = 32;

/* field order, matching PresetDef::v -- consumed by applyPreset() */
enum PresetField {
    PF_RATIO = 0,
    PF_BRIGHT = 1,
    PF_BITE = 2,
    PF_TONE = 3,
    PF_ATTACK = 4,
    PF_DECAY = 5,
    PF_SUSTAIN = 6,
    PF_NOISE = 7,
    PF_MACRO_MODE = 8,
    PF_VOICE_COUNT = 9,
    PF_GLIDE = 10,
    PF_PITCH = 11,
    PF_CRUSH = 12,
    PF_KEYTRACK = 13,
    PF_VOLUME = 14,
    PF_PRESET_GAIN = 15,
    PF_COUNT = 16
};

} /* namespace hank */
#endif
