"""A VCV Rack module's DSP, without its panel, for an MPC port (steve/tools/rack, 2026-10-02).
   python3 extract_module.py <Module.cpp> <WidgetStruct> <out.hpp> [<plugin.hpp> <HelperStruct> ...]
Copies <Module.cpp> up to `struct <WidgetStruct>` (the panel/UI code, which needs the whole Rack GUI) unchanged, drops
its `#include "plugin.hpp"`, prepends any helper structs named from the plugin's plugin.hpp, and includes
rack_shim.hpp instead of rack.hpp. The result compiles against the shim; the original file stays next to it."""
import re, sys

src, widget, out = sys.argv[1:4]
helpers = sys.argv[4:]
s = open(src).read()
body = s[:s.index("struct %s" % widget)].replace('#include "plugin.hpp"\n', "")
extra = ""
if helpers:
    plug = open(helpers[0]).read()
    for name in helpers[1:]:
        m = re.search(r"struct %s \{.*?\n\};\n" % re.escape(name), plug, re.S)
        if not m:
            sys.exit("%s: no struct %s" % (helpers[0], name))
        extra += m.group(0) + "\n"
open(out, "w").write("// %s's DSP for an MPC port: %s up to its panel widget, unchanged%s; compiled against\n"
                     "// steve/tools/rack/rack_shim.hpp. Generated by steve/tools/rack/extract_module.py.\n"
                     "#pragma once\n#include \"rack_shim.hpp\"\nusing namespace rack;\n\n%s%s"
                     % (widget.replace("Widget", ""), src.split("/")[-1],
                        (", plus " + ", ".join(helpers[1:]) + " from plugin.hpp") if helpers[1:] else "", extra, body))
print("wrote", out)
