/* param_names.h — GENERATED by tools/gen_param_names.mjs. DO NOT EDIT.
 *
 * Lowercased SYNTHPARAMETERS names in enum order, which is exactly the
 * attribute vocabulary TAL writes into a .noisemakerpreset <program> element.
 * Used by the importer to resolve an attribute name to its engine slot.
 *
 * 92 of 92 slots named. Regenerate: node tools/gen_param_names.mjs
 */
#ifndef NM_PARAM_NAMES_H
#define NM_PARAM_NAMES_H

#define NM_PARAM_NAME_COUNT 92

static const char *const NM_PARAM_NAMES[NM_PARAM_NAME_COUNT] = {
    "unused1",
    "volume",
    "filtertype",
    "cutoff",
    "resonance",
    "keyfollow",
    "filtercontour",
    "filterattack",
    "filterdecay",
    "filtersustain",
    "filterrelease",
    "ampattack",
    "ampdecay",
    "ampsustain",
    "amprelease",
    "osc1volume",
    "osc2volume",
    "osc3volume",
    "oscmastertune",
    "osc1tune",
    "osc2tune",
    "osc1finetune",
    "osc2finetune",
    "osc1waveform",
    "osc2waveform",
    "oscsync",
    "lfo1waveform",
    "lfo2waveform",
    "lfo1rate",
    "lfo2rate",
    "lfo1amount",
    "lfo2amount",
    "lfo1destination",
    "lfo2destination",
    "lfo1phase",
    "lfo2phase",
    "osc2fm",
    "osc2phase",
    "osc1pw",
    "osc1phase",
    "transpose",
    "freeadattack",
    "freeaddecay",
    "freeadamount",
    "freeaddestination",
    "lfo1sync",
    "lfo1keytrigger",
    "lfo2sync",
    "lfo2keytrigger",
    "portamento",
    "portamentomode",
    "voices",
    "velocityvolume",
    "velocitycontour",
    "velocitycutoff",
    "pitchwheelcutoff",
    "pitchwheelpitch",
    "ringmodulation",
    "chorus1enable",
    "chorus2enable",
    "reverbwet",
    "reverbdecay",
    "reverbpredelay",
    "reverbhighcut",
    "reverblowcut",
    "oscbitcrusher",
    "highpass",
    "detune",
    "vintagenoise",
    "panic",
    "unused2",
    "envelopeeditordest1",
    "envelopeeditorspeed",
    "envelopeeditoramount",
    "envelopeoneshot",
    "envelopefixtempo",
    "envelopereset",
    "tab1open",
    "tab2open",
    "tab3open",
    "tab4open",
    "filterdrive",
    "delaywet",
    "delaytime",
    "delaysync",
    "delayfactorl",
    "delayfactorr",
    "delayhighshelf",
    "delaylowshelf",
    "delayfeedback",
    "presetload",
    "presetsave",
};

/* ---- Aliases -------------------------------------------------------------
 * TAL has shipped more than one attribute vocabulary. Measured over a
 * 442-preset corpus there are exactly two, splitting 321 / 121, and they
 * differ in two ways:
 *
 *   1. CASE. The 121-file vocabulary writes delayfactorR, envelopeOneShot,
 *      lfo1Phase and lfo2Phase. The lookup below is therefore
 *      case-insensitive -- an exact-match lookup silently drops those four
 *      real parameters from every one of those presets. (The off-device
 *      factory generator never hit this because it resolves via
 *      enumMap[k.toUpperCase()], which is case-insensitive by construction.)
 *
 *   2. One genuine RENAME: velocityfilter <-> velocitycutoff. They never
 *      co-occur, and both vocabularies carry velocityvolume and
 *      velocitycontour, so by elimination velocityfilter IS VELOCITYCUTOFF
 *      (the wrapper labels that param "Vel > Cutoff" -- same control).
 *
 * Attributes in neither table (midiclear / midilearn / midilock / unknown)
 * are GUI state with no engine slot and are safely ignored -- but the
 * importer counts them, so a THIRD vocabulary shows up as a number rather
 * than as silently missing sound. */
typedef struct { const char *name; int index; } nm_param_alias_t;

static const nm_param_alias_t NM_PARAM_ALIASES[] = {
    { "velocityfilter", 54 },   /* == velocitycutoff */
};
#define NM_PARAM_ALIAS_COUNT ((int)(sizeof(NM_PARAM_ALIASES) / sizeof(NM_PARAM_ALIASES[0])))

static inline int nm_ci_eq(const char *cand, const char *name, int len) {
    int j = 0;
    for (; j < len && cand[j]; j++) {
        char a = cand[j], b = name[j];
        if (b >= 'A' && b <= 'Z') b = (char)(b - 'A' + 'a');   /* cand is already lower */
        if (a != b) return 0;
    }
    return j == len && cand[j] == '\0';
}

/* Attribute name -> engine index, or -1. Linear scan: called once per
 * attribute per preset against ~92 entries, which is noise next to the file
 * read itself. */
static inline int nm_param_index(const char *name, int len) {
    for (int i = 0; i < NM_PARAM_NAME_COUNT; i++) {
        const char *cand = NM_PARAM_NAMES[i];
        if (cand && nm_ci_eq(cand, name, len)) return i;
    }
    for (int i = 0; i < NM_PARAM_ALIAS_COUNT; i++) {
        if (nm_ci_eq(NM_PARAM_ALIASES[i].name, name, len))
            return NM_PARAM_ALIASES[i].index;
    }
    return -1;
}

#endif /* NM_PARAM_NAMES_H */
