#!/usr/bin/env python3
"""Write docs/parameter-numbers.md: every instrument's parameters by number, for Stevequencer 16's PARAM lanes.
    python3 tools/param-numbers.py          (after tools/build.sh: it reads each plugin's build/params.h)
A plugin's parameter n (P n) is its n-th VST parameter, the order MPC lists them in; this repo's wrapper takes NRPN n-1
as that parameter, on any page. Left out: what NRPN can't set (pop-up open flags, step buttons, text readouts).
The page is the first screen page the control is on ("-": not on the screen, automation only)."""
import glob
import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INSTRUMENTS = ["schwung/instruments/*", "mutable-instruments/rings", "mutable-instruments/elements", "mpc-ports/*"]


def params_h(path):
    """[(key, name, momentary, string_display, min, max, step_target, popup_of)] in VST order"""
    src = open(path).read()
    rows = []
    for row in re.findall(r"^\s*\{(\".*)\},\s*$", src.split("PARAMS[] = {", 1)[1], re.M):
        f = [x.strip() for x in re.findall(r'"(?:[^"\\]|\\.)*"|[^,]+', row)]
        rows.append((f[0].strip('"'), f[1].strip('"').replace('\\"', '"'), f[8] == "1", f[9] == "1",
                     float(f[3].rstrip("f")), float(f[4].rstrip("f")), int(f[11]), int(f[13])))
    return rows


def pages(layout):
    """key -> the first tab it's on"""
    out, tab = {}, None
    for line in open(layout):
        line = line.strip()
        m = re.match(r"\[tab (.+)\]$", line)
        if m:
            tab = m.group(1)
            continue
        if not tab:
            continue
        keys = re.findall(r"\bkey=([^\s]+)", line)
        m = re.match(r'qlinks\s+"[^"]+"\s*=\s*(.+)$', line)
        if m:
            keys += [k.strip() for k in m.group(1).split(",")]
        for k in keys:
            out.setdefault(k, tab)
    return out


def plugin_name(d):
    return json.load(open(os.path.join(d, "vst.json")))["name"]


def main():
    dirs = sorted({d for pat in INSTRUMENTS for d in glob.glob(os.path.join(REPO, pat)) if os.path.isfile(os.path.join(d, "vst.json"))},
                  key=lambda d: plugin_name(d).split("] ", 1)[-1].lower())
    out = ["# Parameter numbers", "",
           "Every parameter of this repo's instruments by number, for **Stevequencer 16**'s lanes: set a lane's DEST to",
           "**PARAM** and its NUMBER to the parameter's **P** number below. The instrument's track takes Stevequencer 16's port",
           "as its MIDI input (as for the notes); the lane then moves that parameter, on any page of the instrument, with no",
           "MIDI learn. (Under the hood: NRPN P-1, which every plugin here takes as that parameter.)", "",
           "P numbers follow MPC's own parameter list for the plugin (the order it saves projects in), and never change for a",
           "plugin you have: new parameters are only ever added at the end. *Page* is where the control is on the screen",
           "(\"-\": not on the screen, but still automatable). Generated by `tools/param-numbers.py` from the builds.", ""]
    missing = []
    for d in dirs:
        h = os.path.join(d, "build", "params.h")
        if not os.path.exists(h):
            missing.append(os.path.relpath(d, REPO))
            continue
        where = pages(os.path.join(d, "layout.conf")) if os.path.exists(os.path.join(d, "layout.conf")) else {}
        rows = []
        for i, (key, name, mom, text, lo, hi, step, popup) in enumerate(params_h(h)):
            if popup >= 0 or step >= 0 or (text and hi <= lo):
                continue
            rows.append("| P%d | %s%s | %s |" % (i + 1, name.strip() or key, " (button)" if mom else "", where.get(key, "-")))
        name = plugin_name(d).split("] ", 1)[-1]
        rel = os.path.relpath(d, REPO)
        out += ["<details><summary><b>%s</b> (%d parameters)</summary>" % (name, len(rows)), "",
                "[%s](../%s/)" % (rel, rel), "", "| P | Parameter | Page |", "|---|---|---|"] + rows + ["", "</details>", ""]
    with open(os.path.join(REPO, "docs", "parameter-numbers.md"), "w") as f:
        f.write("\n".join(out))
    print("docs/parameter-numbers.md: %d instruments%s" % (len(dirs) - len(missing),
                                                           ("; not built: " + ", ".join(missing)) if missing else ""))


if __name__ == "__main__":
    main()
